In [ ]:
#check the latest python version
!python --version

Python 3.10.6


In [ ]:
#Q1
import numpy as np
a = np.random.random((65000,10000))
print(a)

[[0.958577   0.27720837 0.43526178 ... 0.34363726 0.87684924 0.25335528]
 [0.91000469 0.4147764  0.59675579 ... 0.09698338 0.46887301 0.91407552]
 [0.23425463 0.85350722 0.29815003 ... 0.2981242  0.9213966  0.4822119 ]
 ...
 [0.85274708 0.14136397 0.33773017 ... 0.57238746 0.06580218 0.40792371]
 [0.81938741 0.66238656 0.308056   ... 0.52237749 0.93092109 0.1921705 ]
 [0.4915191  0.23754008 0.16255771 ... 0.74504077 0.34901362 0.84457227]]


In [ ]:
#Q2
array = [[5, 8, 10],[2, 0, 9],[5, 4, 2], [2, 3, 9]]
a = array[0] #storing 1st row
b = array[1:len(array)] #storing the rest of the rows
d = dict() #creating a dictionary
for i in range(0,len(a)):
  d[a[i]] = b[i]
print(d)

{5: [2, 0, 9], 8: [5, 4, 2], 10: [2, 3, 9]}


In [ ]:
#Q3
from collections import defaultdict
array = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
d = defaultdict(list)
for element in array:
  d[element].append(element)
result = list(d.values()) #list of values of specific keys in a dictionary
print(result)

[[1], [2, 2], [3, 3, 3], [4, 4, 4, 4]]


In [48]:
#Q4
import numpy as np
array1 = np.random.random((1000,1000))
array2 = np.random.random((1000,1000))
print("Addition: ")
print(array1+array2)
print("Subtraction: ")
print(array1-array2)

Addition: 
[[0.93638174 0.54933317 1.16257108 ... 1.39062475 0.53904122 1.09405703]
 [1.21282828 1.25198364 1.40748045 ... 0.44763232 0.9788512  0.37796018]
 [0.70532879 1.00470047 1.28320223 ... 1.03785567 0.79880939 1.17156034]
 ...
 [1.00633094 0.2611285  1.38938092 ... 1.81701902 0.50783722 1.69231418]
 [0.61701389 1.37579628 1.40066969 ... 1.91375335 1.48533086 0.73802334]
 [1.72038021 1.10807198 1.17094093 ... 1.01226004 1.77908334 1.01997589]]
Subtraction: 
[[-0.32281161 -0.20218079 -0.83422057 ... -0.45966649  0.43636992
   0.70624731]
 [-0.64375796  0.59158923  0.48698245 ... -0.3459832   0.93787022
  -0.13623894]
 [-0.23459189  0.89875119  0.15977811 ... -0.13270813 -0.69555571
   0.58125132]
 ...
 [-0.79199709 -0.04730909 -0.46129915 ... -0.13981859 -0.2792478
   0.0640283 ]
 [-0.05462354  0.46227907 -0.40126645 ...  0.01414009  0.2726721
   0.05007866]
 [ 0.15390511 -0.45544092  0.62128175 ...  0.47277799  0.09788438
   0.7967394 ]]


In [47]:
#Q5
import numpy as np
n = 1000
matrix = np.zeros((n,n), dtype = int)
for i in range(n):
  for j in range(n):
    if(i+j)%2==0:
      matrix[i][j] = 2
    else:
      matrix[i][j] = 1
print(matrix)

[[2 1 2 ... 1 2 1]
 [1 2 1 ... 2 1 2]
 [2 1 2 ... 1 2 1]
 ...
 [1 2 1 ... 2 1 2]
 [2 1 2 ... 1 2 1]
 [1 2 1 ... 2 1 2]]


In [43]:
#Q6
array = [[5, 8, 10],[2, 0, 9],[5, 4, 2], [2, 3, 9]]
print(np.sum(array, axis=0))

[14 15 30]
